# Material for MkDocs ENGLISH configuration file

# Project information
site_name: ' Blockchain 101s '
site_url: https://github.com/lilchichi/101s
site_author: 'lilchichi'
site_description: ' Blockchain 101s '

# Project directories
docs_dir: '101-s'
site_dir: '101-s'

# Repository
repo_name: '101s'
repo_url: https://github.com/lilchichi/101s

nav:
  - Home: '../readme.md'
  - Blockchain 101: '../blockchain.md'

# Theme configuration
theme:
  name: material
  language: en

  # Material for MkDocs features
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
