# Material for MkDocs ENGLISH configuration file

# Project information
site_name: ' Blockchain 101s '
site_url: https://github.com/lilchichi/101s
site_author: 'lilchichi'
site_description: ' Blockchain 101s '

# Repository
repo_name: '101s'
repo_url: https://github.com/lilchichi/101s

nav:
  - Home: 'readme.md'
  - Blockchain 101: 'blockchain.md'

# Theme configuration
theme:
  name: material
  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: deep orange
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

    # Custom admonitions (callouts) require "Insiders" subscription
    admonition:
      # note: fontawesome/solid/sticky-note
      # abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      # success: fontawesome/solid/check
      # question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      # failure: fontawesome/solid/bomb
      # danger: fontawesome/solid/skull
      # bug: fontawesome/solid/robot
      # example: fontawesome/solid/flask
      # quote: fontawesome/solid/quote-left

  # Material for MkDocs features
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  - meta
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - toc:
      toc_depth: 2

# Theme customization
extra_css:
  - assets/stylesheets/extra.css

# Transaltions (intentionally disabled)
extra:
  #  alternate:
  #      # Switch to English
  #    - name: English
  #      link: https://jorge-campo.github.io/material-mkdocs3/en/
  #      lang: en
  #
  #    # Switch to Spanish
  #    - name: Spanish
  #      link: https://jorge-campo.github.io/material-mkdocs3/es/
  #      lang: es

  # Footer icons and links
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ethstatus
      name: Status on Twitter
    - icon: material/web
      link: https://status.im
      name: Status website
    - icon: material/chat
      link: https://join.status.im/chat/public/status

# Plugins
plugins:
  - search:
      lang: en
